### ISSUE TITLE
Incomplete parsing for new XML  format and XSD  schema in aiida quantumespresso

### ISSUE THREAD

**Issue by mikeatm** [marvel-nccr/quantum-eden#36]
This issue:  https://github.com/aiidateam/aiida-quantumespresso/issues/7   will cause problems for the yambo convergence workflows,  since they depend on information thats not provided when using QE 6.x with the new schema,  (number of electrons, whether calc is spin polarised ...). 
@AntimoMarrazzo  any  thoughts on how to get around this?

**Comment by AntimoMarrazzo** [comment]
In the VM espresso *must* be compiled with the old xml format through the D__OLDXML in the make.inc .

**Comment by ltalirz** [comment]
Ok, I think for the time being this can be a solution, I'll take care of it.
Please don't postpone further tests until the next release candidate - you can easily recompile QE with the changed setting.
