### ISSUE TITLE
The MoS2 structure is not a film if read in. pbc=(True,True, True), instead of (True, True, False)

### ISSUE THREAD

**Issue by broeder-j** [marvel-nccr/quantum-eden#37]
Also might be nice if per convention the surface is aligned in z-direction

**Comment by broeder-j** [comment]
In general for films it is way harder to get interoperability between different methods. Conventions might help, or everybody has to implement quite some logic.

**Comment by ltalirz** [comment]
I agree that using z as the surface normal is a good convention.
As for the amount of vacuum needed between layers, this may indeed depend on the method.
@AntimoMarrazzo Please have a look.

**Comment by ltalirz** [comment]
closed in aiidateam/aiida-max-examples#1
